name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Run tests with race detector
        run: go test -race -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        run: go build -v ./...

  cross-build:
    name: Cross-platform Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -o build/dotme-linux-amd64 .

      - name: Build for Linux (arm64)
        run: GOOS=linux GOARCH=arm64 go build -o build/dotme-linux-arm64 .

      - name: Build for macOS (amd64)
        run: GOOS=darwin GOARCH=amd64 go build -o build/dotme-macos-amd64 .
        
      - name: Build for macOS (arm64)
        run: GOOS=darwin GOARCH=arm64 go build -o build/dotme-macos-arm64 .

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o build/dotme-windows-amd64.exe .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/